apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-consumer-web-dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/blankpge/spring-sensor-rabbit.git
      ref:
        branch: feature-1
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

